#variables

#variables

$strDisplayName
$strUPN
$strObjectID
$strAppRoleAssignments = ""
$strAuthMethodId
$strAuthMethodEmail 
$strAuthMethodPhone
$strAuthMethodAuthenticator
$strAuthMethodHelloForBiz
$strBirthday
$strEmployeeID
$strEmployeeHireDate
$strGivenName
$strJobTitle
$strLicenses
$strMemberOfSecurityGroup
$strMemberOf365Group
$strEmailAddress
$strManagedAppRegistrations
$strManagedBy
$strOauthPermissionGrants
$strOnPremDnAttribute
$strOnPremExtension1
$strOnPremExtension2
$strOnPremExtension3
$strOnPremExtension4
$strOnPremExtension5
$strOnPremExtension6
$strOnPremExtension7
$strOnPremExtension8
$strOnPremExtension9
$strOnPremExtension10
$strOnPremExtension11
$strOnPremExtension12
$strOnPremExtension13
$strOnPremExtension14
$strOnPremExtension15
$strOnPremImmutableID
$strOnPremLastSyncTime
$strOnPremProvisioningErrors
$strOnPremSamAccountName
$strOnPremSID
$strOneNotes
$strOtherEmails
$strOwnedDevices
$strOwnedObjects
$strPasswordPolicies
$objPhoto
$strProxyAddresses
$strRegisteredDevices
$strResponsibilities
$strSecurityIdentifier
$strState
$strStreetAddress
$strSurname